### ISSUE TITLE
Replicate board on another user window

### ISSUE THREAD

**Issue by abdulrauf11** [WebFactoryMk/ng2-canvas-whiteboard#1]
How can I use the coordinates produced by the OnBatchUpdate event, to replicate/update the board on another browser?

**Comment by Peshou** [comment]
The onBatchUpdates() event returns an Array<CanvasWhiteboardUpdate> which can be used by the CanvasWhiteboard drawUpdates(CanvasWhiteboardUpdate[]) method to draw on a canvas

**Comment by Peshou** [comment]
The idea with another browser is that you need to devise a Mechanism to send the updates to the other client, mainly WebRTC implementations
