### ISSUE TITLE
No onSave event emitter

### ISSUE THREAD

**Issue by gubbigubbi** [webfactorymk/ng2-canvas-whiteboard#15]
Awesome code - Reading through the documentation - there doesn't seem to be an output event for when the save button is pressed - should one be added?

In the example they attach the saving technique to the undo event but this probably isnt the best place to do this.

**Comment by gubbigubbi** [comment]
Looking through the code - I can see that the downloadImage() method is called when the save button is pressed - it would be really helpful if there could also be an event emitter attached to this too.

**Comment by Peshou** [comment]
Hi,
Sure, i will add the emitter and add an option flag if you do not want to download the image right away

**Comment by Peshou** [comment]
These changes were added in the newest version (v1.4.1). Please try them out and see if everything is okay so we can close the issue

**Comment by gubbigubbi** [comment]
Perfect - your code is super readable too
