### ISSUE TITLE
How i can Fill canvas with dynamic color 

### ISSUE THREAD

**Issue by manojbhardwaj** [webfactorymk/ng2-canvas-whiteboard#16]
How i can Fill canvas with dynamic color

**Comment by Peshou** [comment]
Hi,
Do you mean fill the canvas on start up so it is not white, or have an option that fills it with a particular color ?

**Comment by Peshou** [comment]
Version 1.4.2 contains the added input for the background color, and in this repo in releases you can see the release note and see where this change will be affected

**Comment by manojbhardwaj** [comment]
OK got it and work for me thank you Peshou  you are awesome

**Comment by manojbhardwaj** [comment]
![capture](https://user-images.githubusercontent.com/12440116/33414781-ce32a6cc-d5b8-11e7-838b-ee8f855416c1.PNG)

Great and  finally i made my canvas using ng2-canvas-whiteboard Thank you

**Comment by Peshou** [comment]
Thanks for the appreciation and being part of the community.

Cheers :).
