### ISSUE TITLE
make color transparent

### ISSUE THREAD

**Issue by shekharramola** [webfactorymk/ng2-canvas-whiteboard#18]
Hi, I am using ng2-canvas-whiteboard for painting on an image however If I paint it then I can not see the image.  Actually what I want to do is to make the color transparent.

I tried to add opacity in your createColorPalette function.. however it is not working as intended.
I tried to edit this function

` CanvasWhiteboardColorPickerComponent.prototype.createColorPalette = function() {
        var gradient = this._context.createLinearGradient(0, 0, this._context.canvas.width, 0);
        gradient.addColorStop(0.6, "rgb(255,0,0 , 0.3)");
        gradient.addColorStop(0.15, "rgb(255,0,255, 0.3)");
        gradient.addColorStop(0.33, "rgb(0,     0, 255, 0.3)");
        gradient.addColorStop(0.49, "rgb(0,   255, 255, 0.3)");
        gradient.addColorStop(0.67, "rgb(0,   255,   0, 0.3)");
        gradient.addColorStop(0.84, "rgb(255, 255,   0, 0.3)");
        gradient.addColorStop(1, "rgb(255,   0,   0, 0.3)");
        this._context.fillStyle = gradient;
        this._context.fillRect(0, 0, this._context.canvas.width, this._context.canvas.height);
        gradient = this._context.createLinearGradient(0, 0, 0, this._context.canvas.height);
        gradient.addColorStop(0, "rgba(255, 255, 255, 1, 0.3)");
        gradient.addColorStop(0.5, "rgba(255, 255, 255, 0, 0.3)");
        gradient.addColorStop(0.5, "rgba(0,     0,   0, 0, 0.3)");
        gradient.addColorStop(1, "rgba(0,     0,   0, 1, 0.3)");
        this._context.fillStyle = gradient;
        this._context.fillRect(0, 0, this._context.canvas.width, this._context.canvas.height);
    };`

 can you please tell me how can I achieve that?

**Comment by shekharramola** [comment]
` CanvasWhiteboardColorPickerComponent.prototype.createColorPalette = function() {
        var gradient = this._context.createLinearGradient(0, 0, this._context.canvas.width, 0);
        gradient.addColorStop(0.6, "rgb(255,0,0 , 0.3)");
        gradient.addColorStop(0.15, "rgb(255,0,255, 0.3)");
        gradient.addColorStop(0.33, "rgb(0,     0, 255, 0.3)");
        gradient.addColorStop(0.49, "rgb(0,   255, 255, 0.3)");
        gradient.addColorStop(0.67, "rgb(0,   255,   0, 0.3)");
        gradient.addColorStop(0.84, "rgb(255, 255,   0, 0.3)");
        gradient.addColorStop(1, "rgb(255,   0,   0, 0.3)");
        this._context.fillStyle = gradient;
        this._context.fillRect(0, 0, this._context.canvas.width, this._context.canvas.height);
        gradient = this._context.createLinearGradient(0, 0, 0, this._context.canvas.height);
        gradient.addColorStop(0, "rgba(255, 255, 255, 1, 0.3)");
        gradient.addColorStop(0.5, "rgba(255, 255, 255, 0, 0.3)");
        gradient.addColorStop(0.5, "rgba(0,     0,   0, 0, 0.3)");
        gradient.addColorStop(1, "rgba(0,     0,   0, 1, 0.3)");
        this._context.fillStyle = gradient;
        this._context.fillRect(0, 0, this._context.canvas.width, this._context.canvas.height);
    };`

**Comment by Peshou** [comment]
As a current fix a transparent label has been added in version 2.0.0 please check it out
