### ISSUE TITLE
Support for scaled whiteboard

### ISSUE THREAD

**Issue by lenardfunk** [webfactorymk/ng2-canvas-whiteboard#19]
Hi @Peshou and community,

first of all, I would like to thank you for this package. I am considering using this package in my project. Great work so far.

However, when using the package, I stumbled upon an issue, as I am using `whiteboard` with css ```transform: scale(...)```:

The problem is as follows: If you scale the `whiteboard` (or an HTML element that surrounds it) by applying `transform: scale(...)` the line is **not** drawn at the correct position. This is, because the mouse position is absolute. But the lines are drawn on the image with the original size first and then the whole canvas is scaled (e.g., if you want to draw on `50/50` but you scale it down by `0.5`, you should draw at `100/100`).

Maybe you could add a `scaleFactor` that allows for this feature? 

The solution that worked for me is as follows:

```
let xPos;
let yPos;
if (event) {
    // FireFox
    xPos = event.pageX;
    yPos = event.pageY;
} else {
    // IE
    const windowEvent = window.event as any;
    xPos = windowEvent.x + document.body.scrollLeft - 2;
    yPos = windowEvent.y + document.body.scrollTop - 2;
}

// Set position relative to canvas' top and left offset
const boundingRect = this._canvas.getBoundingClientRect();
xPos -= boundingRect.left;
yPos -= boundingRect.top;

// Reset scale made from css transform-scale, to get mouse position relative to actual canvas size
const scaleWidth = boundingRect.width / this._canvas.width;
const scaleHeight = boundingRect.height / this._canvas.height;
xPos /= scaleWidth;
yPos /= scaleHeight;

return {
    x: xPos,
    y: yPos
}
```

The important part would be:
```
// Reset scale made from css transform-scale, to get mouse position relative to actual canvas size
const scaleWidth = boundingRect.width / this._canvas.width;
const scaleHeight = boundingRect.height / this._canvas.height;
xPos /= scaleWidth;
yPos /= scaleHeight;
```

Whereas, ```this._canvas``` is the actual CanvasHTMLElement.

If you use the mentioned solution with the ```Input() scaleFactor```, you can probably replace ```scaleWidth``` and ```scaleHeight``` with this ```scaleFactor```. I guess the factors for width and height should be equal anyway, otherwise the content may be streched.

If I’m understanding your code correctly the changes would be in the method ```_getCanvasEventPosition``` in the file `canvas-whiteboard.component.ts`.

Thank you in advance for your time and effort,
Cheers

**Comment by lenardfunk** [comment]
Hi @Peshou,

thank you for taking this issue into account!

As you labeled it with high priority, I just want to inquire the state of your development. Have you already started? Is my description understandable? Or can you even already tell the time of the next release including this feature?

Thank you again for your time and effort!
Cheers

**Comment by Peshou** [comment]
The library and these changes are added in version 1.4.3, please check if everything is okay and if we need to do additional changes for them to work.

**Comment by lenardfunk** [comment]
Thanks for your work, @Peshou! I will test it as soon as possible and give you feedback then. But what I can tell from the code, it seems pretty good this way!

**Comment by lenardfunk** [comment]
Scaling works very well! Thanks again! :)

**Comment by Peshou** [comment]
Cheers, i will close this issue now and we will open another one if something else happens.
