### ISSUE TITLE
Image Object-Fit

### ISSUE THREAD

**Issue by marcogrieco** [webfactorymk/ng2-canvas-whiteboard#21]
Hi,
it seems that the canvas use the **_object-fit: cover_** to show the image. There is a way to use the **_object-fit: contain_**?

Thanks in advance.

**Comment by marcogrieco** [comment]
Resolved with AspectRatio property. Thanks

**Comment by eshwerintouch** [comment]
Even after giving AspectRatio = 0 the canvas still cut of some part of the image.
