### ISSUE TITLE
Transparent canvas

### ISSUE THREAD

**Issue by kochax** [webfactorymk/ng2-canvas-whiteboard#23]
It would be nice if we have input param for leaving the canvas background transparent instead of setting default color.

**Comment by Peshou** [comment]
Did you try to make the startingColor="'transparent'" ?

I made a few pictures with that Input and it seemed to work properly.
I added an absolute div element that should show behind the canvas (the same z index, but the canvas is later in the hierarchy), when i set the startingColor input to 'transparent' the div text showed correctly

## Picture 1: startingColor is '#fff'
![screenshot at jun 19 18-14-45](https://user-images.githubusercontent.com/9078620/41610302-28c04798-73ed-11e8-854a-595d96afb11a.png)

## Picture 2: startingColor is 'transparent'
![screenshot at jun 19 18-17-24](https://user-images.githubusercontent.com/9078620/41610342-3e55029c-73ed-11e8-8daa-ff1b5a4be8c5.png)

**Comment by kochax** [comment]
@Peshou 
It's working, I should have tried this

Thanks, btw, nice lib, keep good work on it :)
