### ISSUE TITLE
Not able to create new shapes

### ISSUE THREAD

**Issue by GodsonDsilva** [webfactorymk/ng2-canvas-whiteboard#28]
i am not able to create new drawing, cant understand how to achieve it

**Comment by Peshou** [comment]
Hi, 

Do you want to create your own shape or do you just want to draw?

**Comment by Peshou** [comment]
To instantly draw you can set the drawingEnabled input to true

**Comment by GodsonDsilva** [comment]
I just want to draw freehand drawing on a image and get start co-ordinates
and end co-ordinates and crop the drawing part only ...

Is this possible by using whiteboard

**Comment by Peshou** [comment]
Currently the canvas does not support the cropping function but you could draw and save the image and then crop it manually

**Comment by GodsonDsilva** [comment]
Thanks sir, can I get the co-ordinates when I start drawing and when I end
drawing.

**Comment by Peshou** [comment]
You could listen to the onBatchUpdate output method and find the update which has a type of start and stop and get the coordinates from there.

Other than that i think that i have encapsulated the shapes map and made them private

**Comment by rahinirohini** [comment]
Hi , 
First of all, Great work.
Could you give more explanation about how to get the coordinate points? As of now, onBatchUpdate method i get x,y points. can i know wrt what  x,y points are calculated. say suppose, If user is drawing a square then i want to get the four corner coordinates. It's that possible using whiteboard?
