### ISSUE TITLE
ERROR using Angular 7

### ISSUE THREAD

**Issue by chaucachavez** [webfactorymk/ng2-canvas-whiteboard#50]
Hi, I use Angular CLI: 7.0.1 and Angular: 7.0.0.

When executing: ng serve -o

ERROR in src / .... module.ts (9,40): error TS2307: Cannot find module 'ng2-canvas-whiteboard/index'.

Please help.

**Comment by Peshou** [comment]
Hi, I am sorry but the current version does not have this issue on a new ng generated app. 

Can you please remove the `/index` in the import so it's only 
`import {CanvasWhiteboardModule} from 'ng2-canvas-whiteboard';`

The sample module should look like:
```
.....
...
...
import {CanvasWhiteboardModule} from 'ng2-canvas-whiteboard';

@NgModule({
  declarations: [
    ....
  ],
  imports: [
    ....
    CanvasWhiteboardModule
  ],
  providers: [],
  bootstrap: [....]
})
export class ExampleModule {
}

```

**Comment by Peshou** [comment]
Will close for inactivity, please reopen if this issue still happens.

**Comment by chaucachavez** [comment]
Thanks for the help.
