### ISSUE TITLE
Not working in Angular 9

### ISSUE THREAD

**Issue by thomasblom** [webfactorymk/ng2-canvas-whiteboard#54]
Hello,

I have updated my project to Angular 9 and this package to the latest version (3.0.4 at this time).
After including the module in my AppModule imports, adding the CanvasWhiteboardComponent to the viewProviders and including the code below I got an error.

```
<canvas-whiteboard
    #canvasWhiteboard
    [drawButtonClass]="'drawButtonClass'"
    [drawButtonText]="'Draw'"
    [clearButtonClass]="'clearButtonClass'"
    [clearButtonText]="'Clear'"
    [undoButtonText]="'Undo'"
    [undoButtonEnabled]="true"
    [redoButtonText]="'Redo'"
    [redoButtonEnabled]="true"
    [colorPickerEnabled]="true"
    [saveDataButtonEnabled]="true"
    [saveDataButtonText]="'Save'"
    [lineWidth]="5"
    [strokeColor]="'rgb(0,0,0)'"
    [shouldDownloadDrawing]="true"
    (onBatchUpdate)="sendBatchUpdate($event)"
    (onClear)="onCanvasClear()">
</canvas-whiteboard>
```

The error I get when this initializes:
![Schermafbeelding 2020-02-13 om 11 28 18](https://user-images.githubusercontent.com/8591153/74426100-0f0e3f00-4e55-11ea-8ece-2b0890d678bd.png)

**Comment by preeco-privacy** [comment]
I created a pull request for this issue. 
Hope it will be merged soon.

https://github.com/webfactorymk/ng2-canvas-whiteboard/pull/55

**Comment by Peshou** [comment]
Yup, should be good with version 3.1.0 now, thanks @preeco-privacy. Cheers.
