### ISSUE TITLE
Cannot find name 'CanvasWhiteboardOptions'.

### ISSUE THREAD

**Issue by gayankasun** [webfactorymk/ng2-canvas-whiteboard#61]
I m using `ng2-canvas-whiteboard` 3.1.1 with Angular 9.1.7 . with previous version i have used **CanvasWhiteboardOptions** but when i build the existing code with the latest version i m getting 
### error TS2304: Cannot find name 'CanvasWhiteboardOptions'. can any one have fix for this?

**Comment by Peshou** [comment]
Maybe the automatic import is not working, or the import is wrong, did you make sure that you imported the CanvasWhiteboardOptions interface correctly?

I am using an angular 9 app with 3.1.1 version of the canvas and I have no issue with using the CanvasWhiteboardOptions

```typescript
import {CanvasWhiteboardOptions} from 'ng2-canvas-whiteboard';
```
