### ISSUE TITLE
Hi, how do i stop the pulsating on the draw button? And can i use an icon instead for the button

### ISSUE THREAD

**Issue by sparkyruth** [webfactorymk/ng2-canvas-whiteboard#73]
Hi, 

I currently left a backdoor method called setShouldDraw(shouldDraw: boolean): void but it's a bad idea since you must use a ViewChild reference to use this method.

I will add a drawingEnabled Input() so that u can programatically enable drawing without the user clicking the button (it will still pulsate though), which means that you can hide it as well, or if you just hate the current animation you can override it with none or another animation.

In version 1.4.4 you can find these new changes.

_Originally posted by @Peshou in https://github.com/webfactorymk/ng2-canvas-whiteboard/issues/20#issuecomment-391445655_

**Comment by sparkyruth** [comment]
found solution

**Comment by Sandervanmaurik** [comment]
Did you fix this?

**Comment by sparkyruth** [comment]
Yup

**Comment by Sandervanmaurik** [comment]
Hoe did you add icons instead of text?

**Comment by sparkyruth** [comment]
I used font awesome icons in the class representing the canvas drawing.
like this:
.canvas_whiteboard_button-draw:before{
font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f304";
color: black;
}

**Comment by sparkyruth** [comment]
.canvas_whiteboard_button-draw:before{
font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f304";
color: black;
}
.canvas_whiteboard_button-draw:after{
content:"";
color: black;

}
.canvas_whiteboard_button-draw:focus{
background-color:#5b86e5;
cursor: url('https://.....assets/moreimages/additional/pen.svg'), auto;
color: black;

}
.canvas_whiteboard_button-draw_animated{
-webkit-animation: pulsate 1s ease-out;
animation: none !important;
}
