### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by riyasspalackal** [webfactorymk/ng2-canvas-whiteboard#8]

**Comment by Peshou** [comment]
Hi,
This is a browser CORS related safety feature. This page may give you the help you need
https://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported

![27543183-bfc3fbcc-5a89-11e7-867f-e7340d823657](https://user-images.githubusercontent.com/9078620/31823011-9d269892-b5e5-11e7-8ba5-c5755f92efd3.png)

link to the image post: https://stackoverflow.com/questions/20424279/canvas-todataurl-securityerror

**Comment by gubbigubbi** [comment]
Hey @Peshou would you consider adding the crossOrigin attribute to the canvas object like this:
```
 private _loadImage(callbackFn?: any) {

        this._canDraw = false;
        this._imageElement = new Image();

        // allows CORS
        // refer to mdn docs 
        // https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
        this._imageElement.crossOrigin = 'Anonymous';

        this._imageElement.addEventListener("load", () => {
            this.context.save();
            this._drawImage(this.context, this._imageElement, 0, 0, this.context.canvas.width, this.context.canvas.height, 0.5, 0.5);
            this.context.restore();
            this._drawMissingUpdates();
            this._canDraw = true;
            callbackFn && callbackFn();
            this.onImageLoaded.emit(true);
        });
        this._imageElement.src = this.imageUrl;
    }

I needed to do this to get the toDataUrl() method to working, even once CORS was set to allow * on my server. 
```

**Comment by cca-developer** [comment]
One other possibility for avoiding this issue is to convert the image to a base64 encoded string on the server, then pass that as the imageUrl like:

`[imageUrl]="'data:image/jpg;base64,R0lGODlhEAAQAMQAAORHHOV..."`

If the image is passed like this, then there is no problem saving it again.
